/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVisualSolarPreviewRouteImport } from './routes/api/visual-solar-preview'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppRepRouteImport } from './routes/_app.rep'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualSolarPreviewRoute = ApiVisualSolarPreviewRouteImport.update({
  id: '/api/visual-solar-preview',
  path: '/api/visual-solar-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppRepRoute = AppRepRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/portal': typeof AppPortalRoute
  '/projects': typeof AppProjectsRoute
  '/proposals': typeof AppProposalsRoute
  '/rep': typeof AppRepRoute
  '/tasks': typeof AppTasksRoute
  '/api/visual-solar-preview': typeof ApiVisualSolarPreviewRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/pipeline': typeof AppPipelineRoute
  '/portal': typeof AppPortalRoute
  '/projects': typeof AppProjectsRoute
  '/proposals': typeof AppProposalsRoute
  '/rep': typeof AppRepRoute
  '/tasks': typeof AppTasksRoute
  '/api/visual-solar-preview': typeof ApiVisualSolarPreviewRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/proposals': typeof AppProposalsRoute
  '/_app/rep': typeof AppRepRoute
  '/_app/tasks': typeof AppTasksRoute
  '/api/visual-solar-preview': typeof ApiVisualSolarPreviewRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/commissions'
    | '/dashboard'
    | '/pipeline'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/rep'
    | '/tasks'
    | '/api/visual-solar-preview'
    | '/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/commissions'
    | '/dashboard'
    | '/pipeline'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/rep'
    | '/tasks'
    | '/api/visual-solar-preview'
    | '/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/commissions'
    | '/_app/dashboard'
    | '/_app/pipeline'
    | '/_app/portal'
    | '/_app/projects'
    | '/_app/proposals'
    | '/_app/rep'
    | '/_app/tasks'
    | '/api/visual-solar-preview'
    | '/_app/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiVisualSolarPreviewRoute: typeof ApiVisualSolarPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-solar-preview': {
      id: '/api/visual-solar-preview'
      path: '/api/visual-solar-preview'
      fullPath: '/api/visual-solar-preview'
      preLoaderRoute: typeof ApiVisualSolarPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rep': {
      id: '/_app/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof AppRepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPortalRoute: typeof AppPortalRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppRepRoute: typeof AppRepRoute
  AppTasksRoute: typeof AppTasksRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPortalRoute: AppPortalRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppRepRoute: AppRepRoute,
  AppTasksRoute: AppTasksRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiVisualSolarPreviewRoute: ApiVisualSolarPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
